### ISSUE TITLE
ModuleNotFoundError: No module named 'apscheduler.schedulers.background'

### ISSUE THREAD

**Issue by alisolanki** [ebellocchia/telegram_crypto_price_bot#7]
I ran the following commands:
`python setup.py install`
`pip install telegram_crypto_price_bot`

After this I changed the config.ini file and added api_id, api_hash and bot_token (from BotFather).

Then ran:
`cd app`
`python bot.py`

But the error I am getting is:
```Traceback (most recent call last):
  File "/Users/alisolanki/Program Files/cryptoPriceTelegramBot/app/bot.py", line 26, in <module>
    from telegram_crypto_price_bot import PriceBot, __version__
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/__init__.py", line 5, in <module>
    from telegram_crypto_price_bot.price_bot import PriceBot
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/price_bot.py", line 24, in <module>
    from telegram_crypto_price_bot.bot.bot_base import BotBase
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/bot/bot_base.py", line 31, in <module>
    from telegram_crypto_price_bot.command.command_dispatcher import CommandDispatcher, CommandTypes
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/command/command_dispatcher.py", line 30, in <module>
    from telegram_crypto_price_bot.command.commands import (
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/command/commands.py", line 28, in <module>
    from telegram_crypto_price_bot.coin_info.coin_info_scheduler import (
  File "/opt/homebrew/lib/python3.9/site-packages/telegram_crypto_price_bot-0.3.3-py3.9.egg/telegram_crypto_price_bot/coin_info/coin_info_scheduler.py", line 27, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler.schedulers.background'```

**Comment by alisolanki** [comment]
My pip version: ```pip 22.3.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)```

**Comment by ebellocchia** [comment]
Hi, you don't have to install it via `setup.py`, installing via `pip` is sufficient. Anyway, it seems that, for some reasons, `apscheduler` was not installed, you just have to install it.
